### ISSUE TITLE
Floating Cars

### ISSUE THREAD

**Issue by daxieflatline** [MissyB50/Riverside22#10]
Floating cars outside the grocery near the Petrol station next to field 55

![proShot_2022-07-07_15-37-06](https://user-images.githubusercontent.com/108829506/177800747-813f0bf2-4e82-4dd0-b59b-2f11bacef240.png)
![proShot_2022-07-07_15-39-53](https://user-images.githubusercontent.com/108829506/177801005-5d8eed98-28c2-4884-8d3c-6db55ae420a8.png)

**Comment by daxieflatline** [comment]
Also one in the parking outside the Silo near field 16 (The one with the reported water sounds)

![proShot_2022-07-07_15-58-11](https://user-images.githubusercontent.com/108829506/177805660-446939ee-2cb1-483d-818f-b92badb481da.png)

**Comment by MissyB50** [comment]
fix car issue's
