### ISSUE TITLE
Parking at Cider House

### ISSUE THREAD

**Issue by daxieflatline** [MissyB50/Riverside22#12]
Maybe I had a few too many when I visited but....
Also there's a potted plant right in the middle of the path as you enter.

![proShot_2022-07-07_16-02-33](https://user-images.githubusercontent.com/108829506/177807006-8b2237c8-4b3a-47a0-a3d2-ab5c209f67d3.png)

![proShot_2022-07-07_16-03-14](https://user-images.githubusercontent.com/108829506/177807038-8935af76-bccd-4d8e-9be4-7d571989b318.png)

![proShot_2022-07-07_16-03-43](https://user-images.githubusercontent.com/108829506/177807070-7d359936-3a8d-494a-8302-3044ed815bac.png)

**Comment by MissyB50** [comment]
fixed all issue's
