### ISSUE TITLE
Floating Tree's

### ISSUE THREAD

**Issue by FarmerLee73** [MissyB50/Riverside22#18]
![rs22trees](https://user-images.githubusercontent.com/108911834/177907297-efbadac4-29b6-4e1c-8db7-8e6d89bf6067.jpg)

Floating tree's and wrong ground texture.

**Comment by Volcan95** [comment]
fixed all apart from one at the back and a little bit of ground texturew
![Screenshot_4](https://user-images.githubusercontent.com/108690299/178066466-eae0c5fc-097c-4391-83a3-dcccbde1d396.png)
![Screenshot_6](https://user-images.githubusercontent.com/108690299/178066525-40af5c21-7f9c-48bf-9f0f-f7715fab9d88.png)

**Comment by MissyB50** [comment]
Fixed
