### ISSUE TITLE
main farm bunker 

### ISSUE THREAD

**Issue by BigPeteFarms** [MissyB50/Riverside22#19]

**Comment by BigPeteFarms** [comment]
![20220708175945_1](https://user-images.githubusercontent.com/108957133/178086725-2139c0d9-323a-49e6-9b72-146412de07be.jpg)
![20220708180005_1](https://user-images.githubusercontent.com/108957133/178086729-7aefd0da-f927-48bd-9af5-6ca8a6f89cb7.jpg)
![20220708180408_1](https://user-images.githubusercontent.com/108957133/178086745-7bbe2746-0353-477b-b626-fda47be43153.jpg)

Can not pick any of this up with loader

**Comment by BigPeteFarms** [comment]
![20220708180115_1](https://user-images.githubusercontent.com/108957133/178086770-6eced41e-98fe-4038-b997-50d4da4fabb0.jpg)
![20220708180136_1](https://user-images.githubusercontent.com/108957133/178086772-a7a1fa8c-3a0c-4031-ac8e-300588b7c2a0.jpg)
no collision on walls

**Comment by BigPeteFarms** [comment]
![20220708183519_1](https://user-images.githubusercontent.com/108957133/178086820-09d45815-b967-4315-8122-02eed7a0ed42.jpg)

**Comment by BigPeteFarms** [comment]
![20220708183449_1](https://user-images.githubusercontent.com/108957133/178086847-4b0f96bc-9e29-425a-aba1-e409f482c977.jpg)
looks like about 3.5 million Liters

**Comment by MissyB50** [comment]
now closed
