### ISSUE TITLE
main farm cowbarn

### ISSUE THREAD

**Issue by BigPeteFarms** [MissyB50/Riverside22#20]

**Comment by BigPeteFarms** [comment]
![20220708180938_1](https://user-images.githubusercontent.com/108957133/178086928-ebe27e99-b6c0-4ddd-8681-27d5db32441f.jpg)
![20220708180948_1](https://user-images.githubusercontent.com/108957133/178086931-1bf21d7e-5540-4f6f-a68b-443f2dc5bb77.jpg)
straw full this all that shows up

**Comment by BigPeteFarms** [comment]
![20220708181237_1](https://user-images.githubusercontent.com/108957133/178086970-bedff83a-5232-4519-b1d3-cc68358db1f4.jpg)
fed hay looks like TMR

**Comment by BigPeteFarms** [comment]
![20220708182807_1](https://user-images.githubusercontent.com/108957133/178087002-3931a1f2-b8cd-4d3a-8e08-72ef4f9e88ec.jpg)
only part of water trough shows filled

**Comment by Volcan95** [comment]
Move water trigger icon from location to new with in the new field boundary

**Comment by MissyB50** [comment]
FIXED needs retesting
