### ISSUE TITLE
shop issues and other stuff

### ISSUE THREAD

**Issue by coastalwolf** [MissyB50/Riverside22#23]
no collisions on all hedges, planned?
![20220710201257_1](https://user-images.githubusercontent.com/100929562/178184279-15a9f5f8-c467-466e-832a-22b37fc14d5a.jpg)

Shop issues, was able to take everything out of shop and sell it.
![20220710201406_1](https://user-images.githubusercontent.com/100929562/178183885-cbbc79ae-027a-43ea-8851-1aa962dbed83.jpg)
 
no repair trigger at shop
![20220710202026_1](https://user-images.githubusercontent.com/100929562/178183961-5deb4d83-de18-4d86-a956-89ed7eea7838.jpg)

when buying stuff, it shows in the shop menu tangled up in display equipment
![20220710175947_1](https://user-images.githubusercontent.com/100929562/178184035-d6d61bab-3b3d-4a91-8bab-b18eb1d6ee40.jpg)

mystery water trigger at field 20, it works tho.
![20220710200255_1](https://user-images.githubusercontent.com/100929562/178184070-0e82d54f-eac6-4f92-835b-fa910ee4399b.jpg)

wrong ground texture at forest by field 18?
![20220710181231_1](https://user-images.githubusercontent.com/100929562/178184206-fb95b878-53a7-4ef2-aa0e-105bd4ad58a2.jpg)

no buy/sell locations listed for the following:
Road Salt
Liquid fert
Lime
Herbicide
Stones (at least a sell point, maybe lime production)

Missing bunker on farm by field 76?
![20220710202433_1](https://user-images.githubusercontent.com/100929562/178185231-388f67cb-b640-4e75-844a-ffc86945dd91.jpg)

Walls not right on this bunker at farm by field 76
![20220710202534_1](https://user-images.githubusercontent.com/100929562/178185288-615cbc2d-cd16-4553-9505-4f65bc176512.jpg)

Some AI cars driving through hedge/wall by field 13/17
![20220710205459_1](https://user-images.githubusercontent.com/100929562/178185637-29ab5774-6cf9-4942-b45d-b3843803279f.jpg)

**Comment by Volcan95** [comment]
> no collisions on all hedges, planned? ![20220710201257_1](https://user-images.githubusercontent.com/100929562/178184279-15a9f5f8-c467-466e-832a-22b37fc14d5a.jpg) vehicle can go though but not bales, pallets ect

**Comment by MissyB50** [comment]
> no collisions on all hedges, planned? ![20220710201257_1](https://user-images.githubusercontent.com/100929562/178184279-15a9f5f8-c467-466e-832a-22b37fc14d5a.jpg)

Yes its planned

**Comment by BK-Mods** [comment]
![20220712035241_1](https://user-images.githubusercontent.com/109073982/178343247-2c242caf-cff6-442f-928b-bceaffe72959.jpg)

**Comment by BK-Mods** [comment]
bad texture

**Comment by BK-Mods** [comment]
![proShot_2022-07-12_03-22-19](https://user-images.githubusercontent.com/109073982/178343424-93881ae5-f11f-467c-aaec-48ab6382be70.png)

**Comment by BK-Mods** [comment]
at the grain mill next to field 68

**Comment by coastalwolf** [comment]
still unable to repair at shop. No workshop trigger.
![20220711125217_1](https://user-images.githubusercontent.com/100929562/178347041-d4300a16-34ab-4fb8-ac4a-9f91c03206df.jpg)
![20220711125546_1](https://user-images.githubusercontent.com/100929562/178347366-3527ba8d-a832-4e0e-9488-d9a7dedb303c.jpg)
parked truck in box needing repair. was unable to do any repairs at the shop, got no trigger to do so, no icon's for repair trigger.

**Comment by coastalwolf** [comment]
unable to buy sawmill, was able to walk the entire interior of the sawmill
![20220711132133_1](https://user-images.githubusercontent.com/100929562/178352837-17a38b34-ff82-4981-8827-db90af413e8a.jpg)

spawn point for planks I assume?
![20220711132350_1](https://user-images.githubusercontent.com/100929562/178352936-e0c52670-7be0-4d65-bf50-ed08f20f7e7e.jpg)
