### ISSUE TITLE
buildings

### ISSUE THREAD

**Issue by Volcan95** [MissyB50/Riverside22#26]
![Screenshot_5](https://user-images.githubusercontent.com/108690299/178268627-2b196a74-f7aa-47c3-b9df-4d3499ab32ab.png)

**Comment by Volcan95** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/108690299/178268932-a49dd336-b0be-403b-8756-6d1f6d87f2f7.png)
![Screenshot_6](https://user-images.githubusercontent.com/108690299/178268945-59b9fa3f-0557-41eb-8e88-82abdc21de48.png)

**Comment by MissyB50** [comment]
closed
