### ISSUE TITLE
various

### ISSUE THREAD

**Issue by coastalwolf** [MissyB50/Riverside22#30]
when buying vehicles it messes with display/new farmer machines in shop
![20220714142541_1](https://user-images.githubusercontent.com/100929562/179099870-a7392157-1b3d-44ab-9556-528608af3d1b.jpg)

Wonky parking map wide
![20220714142751_1](https://user-images.githubusercontent.com/100929562/179099913-4a738baf-8034-4b3e-91a8-9495e06761ef.jpg)

no collision for white pallets and IBC tanks
![20220714142647_1](https://user-images.githubusercontent.com/100929562/179099987-a9f0129d-a687-464b-a81f-3f80acfc57f2.jpg)

decoration? no tip point or fill point at main cattle farm
![20220714153056_1](https://user-images.githubusercontent.com/100929562/179100168-251df4d2-0e44-4c17-909f-182649192160.jpg)

trees in field 28. maybe add a little grass around them if suppose to be there
![20220714142817_1](https://user-images.githubusercontent.com/100929562/179100235-aba14a06-fd16-47d9-92be-48bdebe3433f.jpg)

Cow animation stuttering 
**insert video clip here**

Cow barn won't take straw bales

two different grass heights in horse pasture
![20220714155143_1](https://user-images.githubusercontent.com/100929562/179121783-62bffb3c-925f-4e7c-a648-58aeb71eba24.jpg)

replace hedge with gate since horse trigger is there
![20220714171428_1](https://user-images.githubusercontent.com/100929562/179121838-35028fd8-7006-435f-b246-1842551dfd44.jpg)

Missing gate or hedge by pig farm 
![20220714174352_1](https://user-images.githubusercontent.com/100929562/179124918-8d6ba1d7-c4e2-4df8-97dd-defc89c10af3.jpg)

food troughs partially filled at pig farm
![20220714174942_1](https://user-images.githubusercontent.com/100929562/179124979-b191b05e-28fb-41be-b4e1-3b761664005f.jpg)
![20220714174947_1](https://user-images.githubusercontent.com/100929562/179124981-15cedbbe-d557-4c99-a487-8b00af6b0c26.jpg)

unable to get a trigger for silo at pig farm
![20220714175705_1](https://user-images.githubusercontent.com/100929562/179125501-16c61ec5-db37-4ade-8910-1a3000dcbda8.jpg)

white substance in sheep food trough

![20220714180251_1](https://user-images.githubusercontent.com/100929562/179126038-d9fa942e-a293-44db-8b4f-19f87c20a1fc.jpg)

grass in farmyard and in sheds, garages by field 64 (chicken farm)
![20220714182307_1](https://user-images.githubusercontent.com/100929562/179127896-ce4d5b0b-4d44-463e-86b0-c9898c225cc3.jpg)

half the food trough fills for chickens, possibly not enough food capacity for 1,000 chickens
![20220714182606_1](https://user-images.githubusercontent.com/100929562/179128263-c1d9ec87-7659-46db-ade3-d44a61fa1b0d.jpg)

**Comment by MissyB50** [comment]
Ordered more wonkey parking,
reordering vehicles in shop,
silo will be done saturday morning,
animal feed plane fixed,  Pig water is now auto
my farm will done on saturday

the missing hedge or gate is left liked in case there is a farm to the right of the image

horse pasture,  gate on the other side of the barn, fixed foilage issue

field 28 is grass field, when starting on new farmer, all grass field will be reset
