### ISSUE TITLE
Cow barn

### ISSUE THREAD

**Issue by AusFarmer** [MissyB50/Riverside22#31]
Water not showing in trough outside of barn.
![fsScreen_2022_07_15_14_31_59](https://user-images.githubusercontent.com/108871834/179193707-a12c9dc7-eeba-4183-8967-64041082eb89.png)

Straw spreads outside of barn.
![fsScreen_2022_07_15_15_13_23](https://user-images.githubusercontent.com/108871834/179194063-a571e744-17cf-426f-b37c-1cca784b4fde.png)
![fsScreen_2022_07_15_15_12_58](https://user-images.githubusercontent.com/108871834/179194185-ace9c94c-4be1-4343-bae3-30b5ec12ac8a.png)

**Comment by MissyB50** [comment]
straw plane fixed,
 water through fixed
