### ISSUE TITLE
Issues left to do 

### ISSUE THREAD

**Issue by MissyB50** [MissyB50/Riverside22#32]
dddddd

**Comment by Volcan95** [comment]
Decals on north sell grain (roof)

**Comment by Volcan95** [comment]
Bio Mass Adjust the price up

**Comment by Volcan95** [comment]
Cattle Farm Repair trigger
Remove Manure Heap (player places there own)
Sound Files

Remove Bins to Cereal Factory

**Comment by Volcan95** [comment]
Central Grains Ai spline hide

**Comment by Volcan95** [comment]
Bga Bunker Trigger Move out

**Comment by Volcan95** [comment]
pig silo

**Comment by Volcan95** [comment]
extend cotton shed outwards

**Comment by Volcan95** [comment]
rocks on waterfull

**Comment by Volcan95** [comment]
Main Farms east gate rotate 180

**Comment by Volcan95** [comment]
bga first silo remove collsion from easy shed that was

**Comment by Volcan95** [comment]
feild 5 reduce length

**Comment by Volcan95** [comment]
Water fill plain resize - sheep

**Comment by Volcan95** [comment]
hedge along f12

**Comment by Volcan95** [comment]
Commodity storage silo triggers

**Comment by MissyB50** [comment]
Ai splines redo all plus new

**Comment by coastalwolf** [comment]
Here is what I have found so far. Hope to do more in next day or 2.

chicken farm
grass growing in sheds
![20220722160831_1](https://user-images.githubusercontent.com/100929562/180586631-30109137-518b-4891-a446-3fae3c261c9a.jpg)
![20220722160859_1](https://user-images.githubusercontent.com/100929562/180586633-b08cc73a-061d-4612-941c-4d24f12f7f39.jpg)

light bleed through walls 6 bay shed (same for all 6 bay sheds on all farms)
![20220722161434_1](https://user-images.githubusercontent.com/100929562/180586685-a0e165fd-1dfd-48cb-9ad6-e86592846105.jpg)

gate missing next on field next to chicken farm? (1 screen shot)
![20220722161011_1](https://user-images.githubusercontent.com/100929562/180586720-b6906b59-a8e3-48ac-8dfc-9400b99310e1.jpg)

add custom fence to build menu?
![20220722161336_1](https://user-images.githubusercontent.com/100929562/180586758-7ce89db9-3c2d-47ee-b550-aef0d6958226.jpg)

Farm by field 59
light bleed through 6 bay shed
 
move repair trigger icon to other side of wall closer to the opening? 
![20220722161529_1](https://user-images.githubusercontent.com/100929562/180586830-797b2895-5b97-4d9e-8dfb-60a652aed097.jpg)

light bleed through into L shaped shed from 6bay shed behind it (1 screen shot)
![20220722161815_1](https://user-images.githubusercontent.com/100929562/180586872-db7b9244-1213-4f0f-9438-a352d19aa331.jpg)

bulk farm shop

central grain
loading dock no interior lights, dark inside
![20220722162320_1](https://user-images.githubusercontent.com/100929562/180586910-387c927f-c162-47f0-ab11-fb66a06da1e0.jpg)

spawned inside grain mill when selected spot from main map
![20220722162734_1](https://user-images.githubusercontent.com/100929562/180586945-fd377716-b9f1-4292-950a-dbd7e82ddbf9.jpg)

Miscellaneous locations
sink in river and walk under water, but swim in lake

**Comment by Volcan95** [comment]
Sounds

**Comment by Volcan95** [comment]
Supermarket add pallets

**Comment by Volcan95** [comment]
Methane point form bga

**Comment by Volcan95** [comment]
Gates at North Sell Point lock till 9am

**Comment by Volcan95** [comment]
silo production remove sell points

**Comment by Volcan95** [comment]
Bulk sell points remove price list

**Comment by Volcan95** [comment]
forest wood chips sell point not working

**Comment by Volcan95** [comment]
check f5 boundary

**Comment by Volcan95** [comment]
wood chip main farm shop increase

**Comment by Volcan95** [comment]
move fill plain / resize on rootcrop to rh sise

**Comment by Volcan95** [comment]
workshop trigger next to spartan farm, farm3 and 300

**Comment by Volcan95** [comment]
fill trigger fuel station
