### ISSUE TITLE
Farm Supplies North

### ISSUE THREAD

**Issue by AusFarmer** [MissyB50/Riverside22#34]
Next to the potatoes, is Sugarbeet cut. I see a pink cover.
![fsScreen_2022_07_16_01_02_03](https://user-images.githubusercontent.com/108871834/179268091-0b8f6525-6e04-4284-89f5-02943b85fded.png)

Around the shop, the are no collisions at the sheds & pallets, the wood stack, the bin, & wire crate.
![fsScreen_2022_07_15_23_34_59](https://user-images.githubusercontent.com/108871834/179268656-fbfea7c6-178b-4ec0-80a9-1a48bacfafe8.png)
![fsScreen_2022_07_15_23_35_15](https://user-images.githubusercontent.com/108871834/179268676-51dc0993-1218-4f6a-952c-2f5c586cba08.png)
![fsScreen_2022_07_15_23_35_39](https://user-images.githubusercontent.com/108871834/179268682-b1d0422c-5633-4ce5-b927-91ef5865a2c2.png)

When buying product from the shop, the trigger/node thingamy jig is a tad out of whack. (Stop laughing. It's 2:15am, I'm tired, but I want to get this to you.)
![fsScreen_2022_07_16_01_23_26](https://user-images.githubusercontent.com/108871834/179270006-558c8efe-5cd9-4d15-a61e-e6d7e3971c8b.png)

Okay, here we go.
At the silo sell point, I hooked up a trailer and went through all products available on easy dev. The following products were not accepted. I don't know if this helps or not, but I have no idea what product its meant to accept.
Olive. Seeds, TMR, Forage, Chaff, Woodchips, Silage, Grass, Hay, Straw, Snow, Road Salt, Urea Fertilizer, Lime, Pig Food, Manure, Mineral Feed, Stones, Solid Fertilizer.

At the unloading bay, I went through all pallets available. the following list was not accepted.
Bread, Butter, Cake, Canola Oil, Cereal, Chaff, Cheese, Chocolate, Clothes, eggs, Fabric, Flour, Furniture, Grape Juice, Grapes, Herbicide, Honey, Lettuce, Lime, Liquid Fertilizer, Manure, Mineral Feed, Olive Oil, Olives, Pig Food, Planks, Poplar, Raisons, Road Salt, Seeds, Silage, Silage Additive, Snow, Solid Fertilizer, Stones, Strawberries, Sugar, Sunflower Oil, Tomatoes, TMR

**Comment by MissyB50** [comment]
fixed closed
