### ISSUE TITLE
2nd cow barn area

### ISSUE THREAD

**Issue by AusFarmer** [MissyB50/Riverside22#35]
Manure heap not working and cannot be sold.

No trigger at silo. Cannot fill silo.

Sheds/garage need ground paint texture tidy up along back wall. (See Pics)
Also have hedge coming through shed walls.
![Cowbarn2](https://user-images.githubusercontent.com/108871834/179343952-6bf0c000-4e8f-4709-bdaa-2952a2f056bf.png)
![fsScreen_2022_07_16_15_32_00](https://user-images.githubusercontent.com/108871834/179343957-70134c31-9770-49b1-aaaa-c9bccd3e007c.png)
![fsScreen_2022_07_16_15_32_29](https://user-images.githubusercontent.com/108871834/179343959-2cd4091d-9421-49b9-ba69-26e1978817c2.png)
![fsScreen_2022_07_16_15_33_13](https://user-images.githubusercontent.com/108871834/179343960-ce5243af-d42d-4dba-81f5-2c8cdb38a03d.png)
![fsScreen_2022_07_16_15_34_01](https://user-images.githubusercontent.com/108871834/179343964-525f6c1a-c30a-46b9-a29e-f3939499e9d2.png)
![fsScreen_2022_07_16_15_34_18](https://user-images.githubusercontent.com/108871834/179343968-fdd5457d-53b6-4324-9f97-8d31768bed82.png)

**Comment by MissyB50** [comment]
closed fixed
