### ISSUE TITLE
Roars Potatoes/ Cereal Factory area

### ISSUE THREAD

**Issue by AusFarmer** [MissyB50/Riverside22#36]
2 Garbage bins seem to be in the middle of nowhere.
![fsScreen_2022_07_16_16_40_27](https://user-images.githubusercontent.com/108871834/179345102-dd58ed90-fe7e-4635-ab53-233df3574ced.png)

You are showing all Sugarbeet and no potatoes.

Its not a massive thing, but the unloading area size is different.
![fsScreen_2022_07_16_16_41_56](https://user-images.githubusercontent.com/108871834/179344990-a5f09c92-55ff-44dc-a1c1-1a9164034242.png)
![fsScreen_2022_07_16_16_42_10](https://user-images.githubusercontent.com/108871834/179344992-5a35189e-3e08-4831-8961-6c031ecf234f.png)

Product coming out from under the edge of the shed.
![fsScreen_2022_07_16_16_40_57](https://user-images.githubusercontent.com/108871834/179344932-c7c459aa-699f-4863-9a52-f5309489c4e5.png)
![fsScreen_2022_07_16_16_41_37](https://user-images.githubusercontent.com/108871834/179344936-980c4157-0403-4c5d-9273-98b64bafe84f.png)

**Comment by MissyB50** [comment]
fixed closed
