### ISSUE TITLE
Central Grains

### ISSUE THREAD

**Issue by AusFarmer** [MissyB50/Riverside22#37]
Cannot use the silo.

PDA trigger puts you inside the building.
![fsScreen_2022_07_16_17_44_47](https://user-images.githubusercontent.com/108871834/179347024-9b41a4c8-f8b3-4a1c-9907-4dd7e39d27a4.png)

The warehouse paint texture needs a tidy up along back wall. (If you want)
![fsScreen_2022_07_16_17_40_38](https://user-images.githubusercontent.com/108871834/179347101-f76a6256-98f3-4ac0-a1f8-597a967d2898.png)

Cars in carpark out of whack.
![fsScreen_2022_07_16_17_43_15](https://user-images.githubusercontent.com/108871834/179347178-b486d389-ddff-4780-9315-5ecd932c1f10.png)

This has nothing to do with Central Grains.
I was going past the river and noticed a plant. This is just my personal opinion, but I think one of the plants in the pic should be in the water a bit further.
![fsScreen_2022_07_16_17_35_43](https://user-images.githubusercontent.com/108871834/179347400-1e93c3a4-d3a3-421a-a716-7a3a6517e6e3.png)

**Comment by MissyB50** [comment]
fixed closed
