### ISSUE TITLE
Farm between fields 58 & 59

### ISSUE THREAD

**Issue by AusFarmer** [MissyB50/Riverside22#38]
Ground Paint texture in sheds/garages.
![fsScreen_2022_07_17_02_28_28](https://user-images.githubusercontent.com/108871834/179365224-68d69c05-7143-4320-8719-ef34ac575009.png)
![fsScreen_2022_07_17_02_29_28](https://user-images.githubusercontent.com/108871834/179365226-d1533166-3b76-4aa6-8c81-f2e0f9eeda21.png)
![fsScreen_2022_07_17_02_32_26](https://user-images.githubusercontent.com/108871834/179365228-6d7a1004-055c-447e-bd1d-93a0c3498008.png)
![fsScreen_2022_07_17_02_33_48](https://user-images.githubusercontent.com/108871834/179365229-1e75879b-ad54-4bbb-b1f6-ff45ba0419b8.png)
![fsScreen_2022_07_17_02_34_12](https://user-images.githubusercontent.com/108871834/179365230-b3f72ffc-ca24-4549-8e8d-793fe5a528aa.png)
![fsScreen_2022_07_17_02_34_34](https://user-images.githubusercontent.com/108871834/179365232-90c2f1f0-4c68-47c6-95f3-9327c1b1bfc7.png)

**Comment by MissyB50** [comment]
fixed closed
