### ISSUE TITLE
Paint Build menu

### ISSUE THREAD

**Issue by AusFarmer** [MissyB50/Riverside22#39]
No name for 4 of the paint textures.
Asphalt Rough, Cobblestone, Concrete Bricks, & Concrete Tiles.
![fsScreen_2022_07_18_15_14_43](https://user-images.githubusercontent.com/108871834/179452279-5c02d533-3ac0-4b5f-8fdb-14baf6fd5d01.png)

**Comment by MissyB50** [comment]
done fixed.
