### ISSUE TITLE
Mixing Mill

### ISSUE THREAD

**Issue by AusFarmer** [MissyB50/Riverside22#41]
When loading TMR etc, the animation is coming out of he wall and not the pipe. The smoke does work. I tried to capture it in a pic but you cannot see it.
Just querying the TMR cycles per month. Is 3600 correct? Only asking as none of the others are that high.
![fsScreen_2022_07_19_00_12_37](https://user-images.githubusercontent.com/108871834/179540756-6251b290-a1d6-4403-88ad-e5b2aaf13cb0.png)

**Comment by MissyB50** [comment]
fixed
