### ISSUE TITLE
Diesel Refinery

### ISSUE THREAD

**Issue by AusFarmer** [MissyB50/Riverside22#42]
No collisions.
![fsScreen_2022_07_19_00_37_45](https://user-images.githubusercontent.com/108871834/179542881-407fdc60-b704-49aa-a0a4-24dd8ea7a5f4.png)

**Comment by MissyB50** [comment]
fixed but not perect

**Comment by AusFarmer** [comment]
You're only human. I just point out what I find. If it can be fixed, all well and good. If not, it is what it is.
Thank you for all you do.
________________________________
