### ISSUE TITLE
Pig Farm

### ISSUE THREAD

**Issue by AusFarmer** [MissyB50/Riverside22#43]
Trees coming through back wall of shed.
No trigger to buy pigs. No PDA trigger.
![fsScreen_2022_07_19_01_24_08](https://user-images.githubusercontent.com/108871834/179555116-9abed0c5-1e3e-4fba-817c-a2b8f0cc728a.png)

**Comment by MissyB50** [comment]
should be there as its inside the gate (inside the pen area)

**Comment by AusFarmer** [comment]
I see the Silo Pig with the Loading and unloading markers.
Just to confirm I am in the correct spot.
![fsScreen_2022_07_19_02_30_30](https://user-images.githubusercontent.com/108871834/179564161-5a7205e3-5a53-40c9-a3a1-a5ab6ddf3b9f.png)

**Comment by MissyB50** [comment]
have bought the land

**Comment by AusFarmer** [comment]
Yes
________________________________

**Comment by Volcan95** [comment]
![pigs](https://user-images.githubusercontent.com/108690299/180026327-f898b4db-d8bb-4389-b5d8-91e88a073804.png)
![Screenshot_1](https://user-images.githubusercontent.com/108690299/180026333-8a8f1b92-f952-47cb-bb95-df6859943119.png)

I have checked and i have them?

**Comment by MissyB50** [comment]
fixed trees closed
