### ISSUE TITLE
Titch's Agri

### ISSUE THREAD

**Issue by AusFarmer** [MissyB50/Riverside22#45]
Tank at rear of building appears to be to low.
![fsScreen_2022_07_19_17_34_27](https://user-images.githubusercontent.com/108871834/179705420-e1d35fa1-c4eb-493f-8841-9e4aae2a7eea.png)
![fsScreen_2022_07_19_17_34_36](https://user-images.githubusercontent.com/108871834/179705433-cd622474-dc39-41f3-90c0-8ec57b69e86d.png)

No collisions on building. Can walk through. (Including tank)
![fsScreen_2022_07_19_17_36_44](https://user-images.githubusercontent.com/108871834/179705700-e11baf62-cbdc-4f05-9eb6-11dcf95345db.png)
![fsScreen_2022_07_19_17_38_27](https://user-images.githubusercontent.com/108871834/179705790-0ff4fd8b-fe45-4e01-a13d-d751f22a692d.png)

2 of the 4 silos don't have collisions. I have marked with yellow paint. (See pic)
![fsScreen_2022_07_19_17_40_35](https://user-images.githubusercontent.com/108871834/179706335-8a0a47f8-9394-4957-8cda-80b3473c5613.png)
![fsScreen_2022_07_19_18_09_48](https://user-images.githubusercontent.com/108871834/179706970-66684dd6-612c-4727-8ec5-e6b4f0e7490c.png)

**Comment by MissyB50** [comment]
done fixed
