### ISSUE TITLE
Chicken Coop

### ISSUE THREAD

**Issue by AusFarmer** [MissyB50/Riverside22#47]
I Cannot buy chickens.
I have purchased the land as you will see in the pics. I don't have the buy trigger marker. 
![fsScreen_2022_07_20_02_37_36](https://user-images.githubusercontent.com/108871834/179812674-6b8d4dba-e611-4dcf-ae13-bb9a7d573241.png)
![fsScreen_2022_07_20_02_38_28](https://user-images.githubusercontent.com/108871834/179812692-d8a70028-942d-4405-9437-fba0584e6e23.png)

Same thing with the pigs.
![fsScreen_2022_07_20_02_52_44](https://user-images.githubusercontent.com/108871834/179812837-d68f40c5-4bc0-4341-8926-425b92afb0ea.png)
![fsScreen_2022_07_20_02_51_33](https://user-images.githubusercontent.com/108871834/179812831-fd0d82cb-322e-442c-8adf-953b83fcc354.png)

**Comment by Volcan95** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/108690299/180027761-124d5a9d-9827-4282-890c-74337c862c39.png)
I Have the chickens

**Comment by AusFarmer** [comment]
I have just redownloaded build 0.999.2 in case I may of had a corrupt download.
Started a new game save, and still I don't have the trigger here or at the pigs.

**Comment by MissyB50** [comment]
i'll ush another version out later tonight after ive done the current issue out standing
