### ISSUE TITLE
Snow Issues and a few others

### ISSUE THREAD

**Issue by coastalwolf** [MissyB50/Riverside22#5]
Snow issues:
Snow inside shop, no snow on roof of shop
no snow on most silos across the map
no snow on roof of houses near field 43 
snow in all riverside garages 
no snow on roofs of most buildings field 59 
snow and grass in garages by field 64 
no snow on building by field 57
snow creating a pothole by field 16 in road 
no snow on domes at BGA
snow lip created by the scale house for BGA
no snow on silo @ mixing mill
no snow on roofs of all buildings at pig farm field 26
no snow on roofs at main bale shop
weird snow covering leading up to the bridge by waterfall
snow missing on roof on most buildings @ main farm
snow divets in road along field 31, road between field 1 & 3
no snow on sheds at sheep farm
no snow on roof of biomass plant, sell point covering tip point
snow inside building covering tip point, no snow on roof
no snow on silo's at north farm shop
no snow on roof at cotton trader and root crop shop at north farm shop
snow inside garage at cow farm field 68. no snow on roof of garage or silo
snow inside Roar's root crop and potato, no snow on the roofs of the buildings also
tip points and fill points covered in snow at all productions and sell points across the map

sounds like walking in water issues:
walking in water field 38
walking in water next to building with silo by field 16
walking in water at main bale shop

other issues:
by field 16, snow inside building, no snow on building or attached silos
lighting issues in 6 bay riverside garages 
no lights inside warehouse, tree's coming through wall, shelfs overlapping with doors, snow texture on roof is off by field 14
able to walk inside of first roll of paper by BGA on the road side of the stack 
BGA not showing up on map PDA or main map
light missing on pole placed on top of the smoke stack?
pig farm not showing on map PDA or main map by field 26
light reflection off of water falls between 9 & 10 normal? (december @ 831am)
some buildings not showing on PDA map or main map at across the map
gate on left as facing the front of the building goes through building at north farm shop
no collisions on pallets or sheds behind building at farm shop

near f16 grass in middle of road

**Comment by MissyB50** [comment]
> sounds like walking in water issues: walking in water field 38 walking in water next to building with silo by field 16 walking in water at main bale shop

further investigation needed supply screenshot of locations

**Comment by Volcan95** [comment]
> lighting issues in 6 bay riverside garages

further investigation needed  - which farm or building was this, screenshots please

**Comment by Volcan95** [comment]
> light reflection off of water falls between 9 & 10 normal? (december @ 831am)

What is wrong exactly, is it water textures or the rocks?

**Comment by coastalwolf** [comment]
light reflecting off of water ![20220706124111_1](https://user-images.githubusercontent.com/100929562/177652488-882d0d69-a923-49ea-86fa-a6ed090f3fcc.jpg)
6 bay garages, all have same issue in the interior, inside on the ends they are dark, if standing at one of garage looking towards the other you can't even see the wall on opposite end of the building with lights on.
![20220706152242_1](https://user-images.githubusercontent.com/100929562/177653280-9abf7e3b-c186-4bea-90c6-aab93247bd38.jpg)
![20220706152219_1](https://user-images.githubusercontent.com/100929562/177653282-103cd3bf-2ed6-48a3-888f-9e651f76c8d6.jpg)
all garages, 3 bay, 6 bay and the L shaped one have lighting bleed through on the back sides. 
![20220706152351_1](https://user-images.githubusercontent.com/100929562/177653409-d427a352-fffe-4b3e-8feb-f46808f4ca24.jpg)
L-shape garage has stuff in it
![20220706152541_1](https://user-images.githubusercontent.com/100929562/177653969-fffa8d7a-40ef-4967-ad9d-103bbdf7bb8c.jpg)
I will have video shortly of water sound issue,files too big for github.

**Comment by coastalwolf** [comment]
Hopefully this will explain the water sound issues. I first heard it without headphones. I left the PDA open large so you can see the locations.

*** all videos are not publicly listed. Will need the link to access them.***

#1
https://youtu.be/w6ROGhk6DEg
#2
https://youtu.be/pM5U68ogtI4
#3
https://youtu.be/_jgmu1qz49A

**Comment by MissyB50** [comment]
> Hopefully this will explain the water sound issues. I first heard it without headphones. I left the PDA open large so you can see the locations.
> 
> *** all videos are not publicly listed. Will need the link to access them.***
> 
> #1 https://youtu.be/w6ROGhk6DEg #2 https://youtu.be/pM5U68ogtI4 #3 https://youtu.be/_jgmu1qz49A

I now under what you still need finish off doing the sounds files are final yet playing with the sound node's

the snow mask's will be the very last thing to do the list not prioty atm

**Comment by MissyB50** [comment]
> light reflecting off of water ![20220706124111_1](https://user-images.githubusercontent.com/100929562/177652488-882d0d69-a923-49ea-86fa-a6ed090f3fcc.jpg)

will take another look at the textures.

**Comment by MissyB50** [comment]
> t missing on pole placed on top of the smoke stack?

Got screen shot for this one???

**Comment by coastalwolf** [comment]
![20220709133810_1](https://user-images.githubusercontent.com/100929562/178122021-e04e1f0b-148d-4498-abdf-e59583aeb80d.jpg)
This is at the mixing mill

**Comment by MissyB50** [comment]
ty

**Comment by MissyB50** [comment]
Closed due to new version out 11/07/22 build 0.988.7

**Comment by MissyB50** [comment]
Closed due to new version out 11/07/22 build 0.988.7
