### ISSUE TITLE
Farm near field 58

### ISSUE THREAD

**Issue by AusFarmer** [MissyB50/Riverside22#50]
There is a tree blocking the entry/exit from a gate.
Have included a pic of the PDA so you can see where I am.
![fsScreen_2022_07_20_23_34_36](https://user-images.githubusercontent.com/108871834/180002958-d63b5316-e043-459f-a914-8db03b9e65be.png)
![fsScreen_2022_07_20_23_31_54](https://user-images.githubusercontent.com/108871834/180003000-ac7a5668-75c0-4e87-a373-71d47302de3d.png)

**Comment by Volcan95** [comment]
Would you want gates other Way?

**Comment by Volcan95** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/108690299/180028499-2dc914d3-bb2a-4955-aa39-24ee0270ecd2.png)
Foliage around the house?

**Comment by MissyB50** [comment]
fixed and done
