### ISSUE TITLE
Farmers Market

### ISSUE THREAD

**Issue by AusFarmer** [MissyB50/Riverside22#54]
More of a query than an issue.
I noticed a flicker as I was driving past.
Look at the colour of the windows. Would that just be the sun hitting the windows? If I exit the vehicle, it all looks normal.
Its only from where I am positioned on the road.
![fsScreen_2022_07_21_19_08_25](https://user-images.githubusercontent.com/108871834/180183292-6249d4f3-3121-49e0-b3f7-8684ef4ff54c.png)
![fsScreen_2022_07_21_19_08_35](https://user-images.githubusercontent.com/108871834/180183310-ab1b4151-5610-42f0-aa69-2b231f2a789c.png)

**Comment by MissyB50** [comment]
it will be either the clip distance's are set to most of the in game are like this not much can do about

**Comment by AusFarmer** [comment]
No Probs. Thank you Missy.
