### ISSUE TITLE
Restaurant

### ISSUE THREAD

**Issue by AusFarmer** [MissyB50/Riverside22#55]
Cars parked need adjusting, and may want to remove some grass from parking lines.
![fsScreen_2022_08_03_15_11_26](https://user-images.githubusercontent.com/108871834/182533399-5f1f8d93-1d69-4e89-86d7-82797a07f224.png)
![fsScreen_2022_08_03_15_13_18](https://user-images.githubusercontent.com/108871834/182533412-e283466a-2a25-4248-ba25-2e23dcfbe06d.png)
![fsScreen_2022_08_03_15_12_14](https://user-images.githubusercontent.com/108871834/182533406-66611b27-a3ed-4ef2-a670-e08c57309288.png)
![fsScreen_2022_08_03_15_12_23](https://user-images.githubusercontent.com/108871834/182533411-96a81b46-2f86-4269-9f0f-572c8cdf3a29.png)

**Comment by MissyB50** [comment]
fixed
