### ISSUE TITLE
Objects inside garage

### ISSUE THREAD

**Issue by AusFarmer** [MissyB50/Riverside22#7]
At the garages between fields 58 & 59, there are objects in the way.
I suggest looking at all the garages in this area in regards to terrain paint types along the sides and back walls. Its not a deal breaker, but if you want to keep them clean, they will need a touch up.
![fsScreen_2022_07_07_22_03_00](https://user-images.githubusercontent.com/108871834/177776395-a9ecbe3a-f73e-4280-af19-37d40bd28d5b.png)
![fsScreen_2022_07_07_22_03_22](https://user-images.githubusercontent.com/108871834/177776413-d5af535a-251c-4f85-8d0f-486fbd6853a7.png)
![fsScreen_2022_07_07_22_05_56](https://user-images.githubusercontent.com/108871834/177776419-b1ad70b5-ee93-4466-a0c5-eee14c9d43c8.png)
![fsScreen_2022_07_07_22_31_06](https://user-images.githubusercontent.com/108871834/177780687-d4a046da-8996-4cc6-af7d-5d016dafe171.png)
![fsScreen_2022_07_07_22_31_46](https://user-images.githubusercontent.com/108871834/177780699-c75a75b7-67cf-4199-bc21-d53b0b6b8665.png)
![fsScreen_2022_07_07_22_33_12](https://user-images.githubusercontent.com/108871834/177780707-4ae67af2-5706-41c3-88fb-b73986a0b1be.png)

**Comment by MissyB50** [comment]
fixed issue
