### ISSUE TITLE
Cannot purchase all of fields 45, 58, & 59

### ISSUE THREAD

**Issue by AusFarmer** [MissyB50/Riverside22#8]
Was looking at purchasing the farm where the garages are that I previously reported.
Please excuse me as I don't know the correct terminology. When I tried to purchase the land the blue buy box doesn't match up with the shape of the field. Again, apologies for my explanation.
This affects the farm between fields 58 & 59, as well as fields 45, 58, & 59. 
The pics will show you what I mean.
Please note where the large cursor is located on the pic, that is where I clicked to bring up the buy box.
![fsScreen_2022_07_07_22_58_21](https://user-images.githubusercontent.com/108871834/177789173-b0edf10c-c4ef-4219-92bf-0031a7272d81.png)
![fsScreen_2022_07_07_22_58_31](https://user-images.githubusercontent.com/108871834/177789180-a9dea69c-25a7-4c38-bfa7-a3f9abb631ff.png)
![fsScreen_2022_07_07_22_59_09](https://user-images.githubusercontent.com/108871834/177789185-51dff017-f024-44c1-8606-e9a7b1c0f56f.png)
![fsScreen_2022_07_07_22_59_22](https://user-images.githubusercontent.com/108871834/177789188-99dc48de-f860-4d3e-85a9-b276cbc2b623.png)
![fsScreen_2022_07_07_22_59_33](https://user-images.githubusercontent.com/108871834/177789189-093ef066-fad9-4921-84a9-15fecaae0ecd.png)

**Comment by MissyB50** [comment]
Old layout on farmlands last thing to do
